### ISSUE TITLE
More strict service URL

### ISSUE THREAD

**Issue by rymsha** [enonic/lib-asset#28]
`/admin/tool/bla/_/service/com.enonic.xp.app.standardidprovider/asset/0000019224f61500/images/enonic.svg` - returns 200, but should 404
Only `/admin/tool/_/service/com.enonic.xp.app.standardidprovider/asset/0000019224f61500/images/enonic.svg` (notice no `bla` in path) should work

for webapps, and closest sites same rules apply.
This also implies adjustment to `assetUrl` function.

Note, however, that in XP8 this is already done, as instead of `service` we'll use `api`

**Comment by ComLock** [comment]
I don't see how this should be handled from inside the service?

Shouldn't rather whatever handles /admin/tool/bla/ return 404 for /admin/tool/bla/* ?

**Comment by rymsha** [comment]
We recently implemented it for API.
We might need to copy our Java code to generate url
As for hanging - service can check that URL matches requirements
